# Generated by Django 4.2.2 on 2023-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_location_lat_remove_location_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(),
        ),
    ]
